
from dataclasses import dataclass
import typing
import typing_extensions

from flytekit.core.annotation import FlyteAnnotation

from latch.types.metadata import NextflowParameter
from latch.types.file import LatchFile
from latch.types.directory import LatchDir, LatchOutputDir

# Import these into your `__init__.py` file:
#
# from .parameters import generated_parameters

generated_parameters = {
    'manifest': NextflowParameter(
        type=str,
        default='./refs/Manifest.txt',
        section_title='Input/output options',
        description='The .tsv file specifying sample matrix filepaths.',
    ),
    'input': NextflowParameter(
        type=str,
        default='./refs/SampleSheet.tsv',
        section_title=None,
        description='The .tsv file specifying sample metadata.',
    ),
    'ensembl_mappings': NextflowParameter(
        type=str,
        default='https://raw.githubusercontent.com/nf-core/test-datasets/scflow/assets/ensembl_mappings.tsv',
        section_title=None,
        description="Optional tsv file containing mappings between ensembl_gene_id's and gene_names's",
    ),
    'ctd_path': NextflowParameter(
        type=str,
        default='https://s3-eu-west-1.amazonaws.com/pfigshare-u-files/28033407/ctd_v1.zip',
        section_title=None,
        description='Cell-type annotations reference file path',
    ),
    'celltype_mappings': NextflowParameter(
        type=typing.Optional[str],
        default='./conf/celltype_mappings.tsv',
        section_title=None,
        description='Optional tsv file specifying manual revisions of cell-type annotations.',
    ),
    'reddim_genes_yml': NextflowParameter(
        type=typing.Optional[str],
        default='./conf/reddim_genes.yml',
        section_title=None,
        description='Optional list of genes of interest in YML format for plotting of gene expression.',
    ),
    'species': NextflowParameter(
        type=str,
        default='human',
        section_title=None,
        description='Input sample species.',
    ),
    'outdir': NextflowParameter(
        type=typing.Optional[typing_extensions.Annotated[LatchDir, FlyteAnnotation({'output': True})]],
        default=None,
        section_title=None,
        description='Outputs directory.',
    ),
    'qc_key_colname': NextflowParameter(
        type=str,
        default='manifest',
        section_title='Quality-Control',
        description='The sample sheet column name with unique sample identifiers.',
    ),
    'qc_factor_vars': NextflowParameter(
        type=str,
        default='seqdate',
        section_title=None,
        description='The sample sheet variables to treat as factors.',
    ),
    'qc_min_library_size': NextflowParameter(
        type=int,
        default=250,
        section_title=None,
        description='Minimum library size (counts) per cell.',
    ),
    'qc_max_library_size': NextflowParameter(
        type=str,
        default='adaptive',
        section_title=None,
        description='Maximum library size (counts) per cell.',
    ),
    'qc_min_features': NextflowParameter(
        type=int,
        default=100,
        section_title=None,
        description='Minimum features (expressive genes) per cell.',
    ),
    'qc_max_features': NextflowParameter(
        type=str,
        default='adaptive',
        section_title=None,
        description='Maximum features (expressive genes) per cell.',
    ),
    'qc_min_ribo': NextflowParameter(
        type=typing.Optional[float],
        default=None,
        section_title=None,
        description='Minimum proportion of counts mapping to ribosomal genes.',
    ),
    'qc_max_ribo': NextflowParameter(
        type=float,
        default=1,
        section_title=None,
        description='Maximum proportion of counts mapping to ribosomal genes.',
    ),
    'qc_max_mito': NextflowParameter(
        type=str,
        default='adaptive',
        section_title=None,
        description='Maximum proportion of counts mapping to mitochondrial genes.',
    ),
    'qc_min_counts': NextflowParameter(
        type=int,
        default=2,
        section_title=None,
        description='Minimum counts for gene expressivity.',
    ),
    'qc_min_cells': NextflowParameter(
        type=int,
        default=2,
        section_title=None,
        description='Minimum cells for gene expressivity.',
    ),
    'qc_drop_unmapped': NextflowParameter(
        type=str,
        default='True',
        section_title=None,
        description='Option to drop unmapped genes.',
    ),
    'qc_drop_mito': NextflowParameter(
        type=str,
        default='True',
        section_title=None,
        description='Option to drop mitochondrial genes.',
    ),
    'qc_drop_ribo': NextflowParameter(
        type=str,
        default='false',
        section_title=None,
        description='Option to drop ribosomal genes.',
    ),
    'qc_nmads': NextflowParameter(
        type=float,
        default=4,
        section_title=None,
        description='The number of MADs for outlier detection.',
    ),
    'amb_find_cells': NextflowParameter(
        type=str,
        default='true',
        section_title='Ambient RNA Profiling',
        description='Enable ambient RNA / empty droplet profiling.',
    ),
    'amb_retain': NextflowParameter(
        type=str,
        default='auto',
        section_title=None,
        description='Upper UMI counts threshold for true cell annotation.',
    ),
    'amb_lower': NextflowParameter(
        type=int,
        default=100,
        section_title=None,
        description='Lower UMI counts threshold for empty droplet annotation.',
    ),
    'amb_alpha_cutoff': NextflowParameter(
        type=float,
        default=0.001,
        section_title=None,
        description='The maximum FDR for the emptyDrops algorithm.',
    ),
    'amb_niters': NextflowParameter(
        type=int,
        default=10000,
        section_title=None,
        description='Number of Monte Carlo p-value iterations.',
    ),
    'amb_expect_cells': NextflowParameter(
        type=int,
        default=3000,
        section_title=None,
        description='Expected number of cells per sample.',
    ),
    'mult_find_singlets': NextflowParameter(
        type=str,
        default='true',
        section_title='Multiplet Identification',
        description='Enable doublet/multiplet identification.',
    ),
    'mult_singlets_method': NextflowParameter(
        type=str,
        default='doubletfinder',
        section_title=None,
        description='Algorithm to use for doublet/multiplet identification.',
    ),
    'mult_vars_to_regress_out': NextflowParameter(
        type=str,
        default='nCount_RNA,pc_mito',
        section_title=None,
        description='Variables to regress out for dimensionality reduction.',
    ),
    'mult_pca_dims': NextflowParameter(
        type=int,
        default=10,
        section_title=None,
        description='Number of PCA dimensions to use.',
    ),
    'mult_var_features': NextflowParameter(
        type=int,
        default=2000,
        section_title=None,
        description='The top n most variable features to use.',
    ),
    'mult_doublet_rate': NextflowParameter(
        type=typing.Optional[float],
        default=None,
        section_title=None,
        description='A fixed doublet rate.',
    ),
    'mult_dpk': NextflowParameter(
        type=int,
        default=8,
        section_title=None,
        description='Doublets per thousand cells increment.',
    ),
    'mult_pK': NextflowParameter(
        type=float,
        default=0.02,
        section_title=None,
        description='Specify a pK value instead of parameter sweep.',
    ),
    'merge_plot_vars': NextflowParameter(
        type=str,
        default='total_features_by_counts,total_counts,pc_mito,pc_ribo',
        section_title='Merge',
        description='Numeric variables for inter-sample metrics.',
    ),
    'merge_facet_vars': NextflowParameter(
        type=str,
        default='NULL',
        section_title=None,
        description='Categorical variables for further sub-setting of plots',
    ),
    'merge_outlier_vars': NextflowParameter(
        type=str,
        default='total_features_by_counts,total_counts',
        section_title=None,
        description='Numeric variables for outlier identification.',
    ),
    'integ_method': NextflowParameter(
        type=str,
        default='Liger',
        section_title='Integration',
        description='Choice of integration method.',
    ),
    'integ_unique_id_var': NextflowParameter(
        type=str,
        default='manifest',
        section_title=None,
        description='Unique sample identifier variable.',
    ),
    'integ_take_gene_union': NextflowParameter(
        type=str,
        default='false',
        section_title=None,
        description='Fill out matrices with union of genes.',
    ),
    'integ_remove_missing': NextflowParameter(
        type=str,
        default='true',
        section_title=None,
        description='Remove non-expressing cells/genes.',
    ),
    'integ_num_genes': NextflowParameter(
        type=int,
        default=3000,
        section_title=None,
        description='Number of genes to find for each dataset.',
    ),
    'integ_combine': NextflowParameter(
        type=str,
        default='union',
        section_title=None,
        description='How to combine variable genes across experiments.',
    ),
    'integ_keep_unique': NextflowParameter(
        type=str,
        default='false',
        section_title=None,
        description='Keep unique genes.',
    ),
    'integ_capitalize': NextflowParameter(
        type=str,
        default='false',
        section_title=None,
        description='Capitalize gene names to match homologous genes.',
    ),
    'integ_use_cols': NextflowParameter(
        type=str,
        default='true',
        section_title=None,
        description='Treat each column as a cell.',
    ),
    'integ_k': NextflowParameter(
        type=int,
        default=30,
        section_title=None,
        description='Inner dimension of factorization (n factors).',
    ),
    'integ_lambda': NextflowParameter(
        type=float,
        default=5,
        section_title=None,
        description='Regularization parameter.',
    ),
    'integ_thresh': NextflowParameter(
        type=float,
        default=0.0001,
        section_title=None,
        description='Convergence threshold.',
    ),
    'integ_max_iters': NextflowParameter(
        type=int,
        default=100,
        section_title=None,
        description='Maximum number of block coordinate descent iterations.',
    ),
    'integ_nrep': NextflowParameter(
        type=int,
        default=1,
        section_title=None,
        description='Number of restarts to perform.',
    ),
    'integ_rand_seed': NextflowParameter(
        type=int,
        default=1,
        section_title=None,
        description='Random seed for reproducible results.',
    ),
    'integ_knn_k': NextflowParameter(
        type=int,
        default=20,
        section_title=None,
        description='Number of neearest neighbours for within-dataset knn graph.',
    ),
    'integ_k2': NextflowParameter(
        type=int,
        default=500,
        section_title=None,
        description='Horizon parameter for shared nearest factor graph.',
    ),
    'integ_prune_thresh': NextflowParameter(
        type=float,
        default=0.2,
        section_title=None,
        description='Minimum allowed edge weight.',
    ),
    'integ_ref_dataset': NextflowParameter(
        type=str,
        default='NULL',
        section_title=None,
        description='Name of dataset to use as a reference.',
    ),
    'integ_min_cells': NextflowParameter(
        type=int,
        default=2,
        section_title=None,
        description='Minimum number of cells to consider a cluster shared across datasets.',
    ),
    'integ_quantiles': NextflowParameter(
        type=int,
        default=50,
        section_title=None,
        description='Number of quantiles to use for normalization.',
    ),
    'integ_nstart': NextflowParameter(
        type=int,
        default=10,
        section_title=None,
        description='Number of times to perform Louvain community detection.',
    ),
    'integ_resolution': NextflowParameter(
        type=int,
        default=1,
        section_title=None,
        description='Controls the number of communities detected.',
    ),
    'integ_dims_use': NextflowParameter(
        type=str,
        default='NULL',
        section_title=None,
        description='Indices of factors to use for shared nearest factor determination.',
    ),
    'integ_dist_use': NextflowParameter(
        type=str,
        default='CR',
        section_title=None,
        description='Distance metric to use in calculating nearest neighbour.',
    ),
    'integ_center': NextflowParameter(
        type=str,
        default='false',
        section_title=None,
        description='Center the data when scaling factors.',
    ),
    'integ_small_clust_thresh': NextflowParameter(
        type=typing.Optional[int],
        default=None,
        section_title=None,
        description='Small cluster extraction cells threshold.',
    ),
    'integ_categorical_covariates': NextflowParameter(
        type=str,
        default='individual,diagnosis,region,sex',
        section_title=None,
        description='Categorical variables for integration report metrics.',
    ),
    'integ_input_reduced_dim': NextflowParameter(
        type=str,
        default='UMAP',
        section_title=None,
        description='Reduced dimension embedding for the integration report.',
    ),
    'reddim_input_reduced_dim': NextflowParameter(
        type=str,
        default='PCA,Liger',
        section_title='Dimensionality Reduction',
        description='Input matrix for dimension reduction.',
    ),
    'reddim_reduction_methods': NextflowParameter(
        type=str,
        default='tSNE,UMAP,UMAP3D',
        section_title=None,
        description='Dimension reduction outputs to generate.',
    ),
    'reddim_vars_to_regress_out': NextflowParameter(
        type=str,
        default='nCount_RNA,pc_mito',
        section_title=None,
        description='Variables to regress out before dimension reduction.',
    ),
    'reddim_umap_pca_dims': NextflowParameter(
        type=int,
        default=30,
        section_title=None,
        description='Number of PCA dimensions.',
    ),
    'reddim_umap_n_neighbors': NextflowParameter(
        type=int,
        default=35,
        section_title=None,
        description='Number of nearest neighbours to use.',
    ),
    'reddim_umap_n_components': NextflowParameter(
        type=int,
        default=2,
        section_title=None,
        description='The dimension of the space to embed into.',
    ),
    'reddim_umap_init': NextflowParameter(
        type=str,
        default='spectral',
        section_title=None,
        description='Type of initialization for the coordinates.',
    ),
    'reddim_umap_metric': NextflowParameter(
        type=str,
        default='euclidean',
        section_title=None,
        description='Distance metric for finding nearest neighbours.',
    ),
    'reddim_umap_n_epochs': NextflowParameter(
        type=int,
        default=200,
        section_title=None,
        description='Number of epochs to us during optimization of embedded coordinates.',
    ),
    'reddim_umap_learning_rate': NextflowParameter(
        type=int,
        default=1,
        section_title=None,
        description='Initial learning rate used in optimization of coordinates.',
    ),
    'reddim_umap_min_dist': NextflowParameter(
        type=float,
        default=0.4,
        section_title=None,
        description='Effective minimum distance between embedded points.',
    ),
    'reddim_umap_spread': NextflowParameter(
        type=float,
        default=0.85,
        section_title=None,
        description='Effective scale of embedded points.',
    ),
    'reddim_umap_set_op_mix_ratio': NextflowParameter(
        type=float,
        default=1,
        section_title=None,
        description='Interpolation to combine local fuzzy sets.',
    ),
    'reddim_umap_local_connectivity': NextflowParameter(
        type=int,
        default=1,
        section_title=None,
        description='Local connectivity required.',
    ),
    'reddim_umap_repulsion_strength': NextflowParameter(
        type=int,
        default=1,
        section_title=None,
        description='Weighting applied to negative samples in embedding optimization.',
    ),
    'reddim_umap_negative_sample_rate': NextflowParameter(
        type=int,
        default=5,
        section_title=None,
        description='Number of negative edge samples to use per positive edge sample.',
    ),
    'reddim_umap_fast_sgd': NextflowParameter(
        type=str,
        default='false',
        section_title=None,
        description='Use fast SGD.',
    ),
    'reddim_tsne_dims': NextflowParameter(
        type=int,
        default=2,
        section_title=None,
        description='Output dimensionality.',
    ),
    'reddim_tsne_initial_dims': NextflowParameter(
        type=int,
        default=50,
        section_title=None,
        description='Number of dimensions retained in the initial PCA step.',
    ),
    'reddim_tsne_perplexity': NextflowParameter(
        type=int,
        default=150,
        section_title=None,
        description='Perplexity parameter.',
    ),
    'reddim_tsne_theta': NextflowParameter(
        type=float,
        default=0.5,
        section_title=None,
        description='Speed/accuracy trade-off.',
    ),
    'reddim_tsne_stop_lying_iter': NextflowParameter(
        type=int,
        default=250,
        section_title=None,
        description='Iteration after which perplexities are no longer exaggerated.',
    ),
    'reddim_tsne_mom_switch_iter': NextflowParameter(
        type=int,
        default=250,
        section_title=None,
        description='Iteration after which the final momentum is used.',
    ),
    'reddim_tsne_max_iter': NextflowParameter(
        type=int,
        default=1000,
        section_title=None,
        description='Number of iterations.',
    ),
    'reddim_tsne_pca_center': NextflowParameter(
        type=str,
        default='true',
        section_title=None,
        description='Center data before PCA.',
    ),
    'reddim_tsne_pca_scale': NextflowParameter(
        type=str,
        default='false',
        section_title=None,
        description='Scale data before PCA.',
    ),
    'reddim_tsne_normalize': NextflowParameter(
        type=str,
        default='true',
        section_title=None,
        description='Normalize data before distance calculations.',
    ),
    'reddim_tsne_momentum': NextflowParameter(
        type=float,
        default=0.5,
        section_title=None,
        description='Momentum used in the first part of optimization.',
    ),
    'reddim_tsne_final_momentum': NextflowParameter(
        type=float,
        default=0.8,
        section_title=None,
        description='Momentum used in the final part of optimization.',
    ),
    'reddim_tsne_eta': NextflowParameter(
        type=int,
        default=1000,
        section_title=None,
        description='Learning rate.',
    ),
    'reddim_tsne_exaggeration_factor': NextflowParameter(
        type=int,
        default=12,
        section_title=None,
        description='Exaggeration factor used in the first part of the optimization.',
    ),
    'clust_cluster_method': NextflowParameter(
        type=str,
        default='leiden',
        section_title='Clustering',
        description='Clustering method.',
    ),
    'clust_reduction_method': NextflowParameter(
        type=str,
        default='UMAP_Liger',
        section_title=None,
        description='Reduced dimension input(s) for clustering.',
    ),
    'clust_res': NextflowParameter(
        type=float,
        default=0.001,
        section_title=None,
        description='The resolution of clustering.',
    ),
    'clust_k': NextflowParameter(
        type=int,
        default=50,
        section_title=None,
        description='Integer number of nearest neighbours for clustering.',
    ),
    'clust_louvain_iter': NextflowParameter(
        type=int,
        default=1,
        section_title=None,
        description='The number of iterations for clustering.',
    ),
    'cta_clusters_colname': NextflowParameter(
        type=str,
        default='clusters',
        section_title='Cell-type Annotation',
        description='SingleCellExperiment clusters colData variable name.',
    ),
    'cta_cells_to_sample': NextflowParameter(
        type=int,
        default=10000,
        section_title=None,
        description='Max cells to sample.',
    ),
    'cta_unique_id_var': NextflowParameter(
        type=str,
        default='individual',
        section_title=None,
        description='A sample metadata unique sample ID.',
    ),
    'cta_celltype_var': NextflowParameter(
        type=str,
        default='cluster_celltype',
        section_title=None,
        description='SingleCellExperiment cell-type colData variable name.',
    ),
    'cta_facet_vars': NextflowParameter(
        type=str,
        default='manifest,diagnosis,sex,capdate,prepdate,seqdate',
        section_title=None,
        description='Cell-type metrics for categorical variables.',
    ),
    'cta_metric_vars': NextflowParameter(
        type=str,
        default='pc_mito,pc_ribo,total_counts,total_features_by_counts',
        section_title=None,
        description='Cell-type metrics for numeric variables.',
    ),
    'cta_top_n': NextflowParameter(
        type=int,
        default=5,
        section_title=None,
        description='Number of top marker genes for plot/table generation.',
    ),
    'dge_de_method': NextflowParameter(
        type=str,
        default='MASTZLM',
        section_title='Differential Gene Expression',
        description='Differential gene expression method.',
    ),
    'dge_mast_method': NextflowParameter(
        type=str,
        default='bayesglm',
        section_title=None,
        description='MAST method.',
    ),
    'dge_min_counts': NextflowParameter(
        type=int,
        default=1,
        section_title=None,
        description='Expressive gene minimum counts.',
    ),
    'dge_min_cells_pc': NextflowParameter(
        type=float,
        default=0.1,
        section_title=None,
        description='Expressive gene minimum cells fraction.',
    ),
    'dge_rescale_numerics': NextflowParameter(
        type=str,
        default='true',
        section_title=None,
        description='Re-scale numeric covariates.',
    ),
    'dge_pseudobulk': NextflowParameter(
        type=str,
        default='false',
        section_title=None,
        description='Pseudobulked differential gene expression.',
    ),
    'dge_celltype_var': NextflowParameter(
        type=str,
        default='cluster_celltype',
        section_title=None,
        description='Cell-type annotation variable name.',
    ),
    'dge_sample_var': NextflowParameter(
        type=str,
        default='manifest',
        section_title=None,
        description='Unique sample identifier variable.',
    ),
    'dge_dependent_var': NextflowParameter(
        type=str,
        default='group',
        section_title=None,
        description='Dependent variable of DGE model.',
    ),
    'dge_ref_class': NextflowParameter(
        type=str,
        default='Control',
        section_title=None,
        description='Reference class of categorical dependent variable.',
    ),
    'dge_confounding_vars': NextflowParameter(
        type=str,
        default='cngeneson,seqdate,pc_mito',
        section_title=None,
        description='Confounding variables.',
    ),
    'dge_random_effects_var': NextflowParameter(
        type=str,
        default='NULL',
        section_title=None,
        description='Random effect confounding variable.',
    ),
    'dge_fc_threshold': NextflowParameter(
        type=float,
        default=1.1,
        section_title=None,
        description='Fold-change threshold for plotting.',
    ),
    'dge_pval_cutoff': NextflowParameter(
        type=float,
        default=0.05,
        section_title=None,
        description='Adjusted p-value cutoff.',
    ),
    'dge_force_run': NextflowParameter(
        type=str,
        default='false',
        section_title=None,
        description='Force model fit for non-full rank.',
    ),
    'dge_max_cores': NextflowParameter(
        type=str,
        default="'null'",
        section_title=None,
        description='Maximum CPU cores.',
    ),
    'ipa_enrichment_tool': NextflowParameter(
        type=str,
        default='WebGestaltR',
        section_title='Impacted Pathway Analysis',
        description='Pathway enrichment tool(s) to use.',
    ),
    'ipa_enrichment_method': NextflowParameter(
        type=str,
        default='ORA',
        section_title=None,
        description='Enrichment method.',
    ),
    'ipa_enrichment_database': NextflowParameter(
        type=str,
        default='GO_Biological_Process',
        section_title=None,
        description='Database(s) to use for enrichment.',
    ),
    'dirich_unique_id_var': NextflowParameter(
        type=str,
        default='individual',
        section_title='Dirichlet Modeling',
        description='Unique sampler identifier.',
    ),
    'dirich_celltype_var': NextflowParameter(
        type=str,
        default='cluster_celltype',
        section_title=None,
        description='Cell-type annotation variable name.',
    ),
    'dirich_dependent_var': NextflowParameter(
        type=str,
        default='group',
        section_title=None,
        description='Dependent variable of Dirichlet model.',
    ),
    'dirich_ref_class': NextflowParameter(
        type=str,
        default='Control',
        section_title=None,
        description='Reference class of categorical dependent variable.',
    ),
    'dirich_var_order': NextflowParameter(
        type=str,
        default='Control,Low,High',
        section_title=None,
        description='Dependent variable classes order.',
    ),
    'plotreddim_reduction_methods': NextflowParameter(
        type=str,
        default='UMAP_Liger',
        section_title='General - Plotting',
        description='Preferred embedding for plots.',
    ),
    'reddimplot_pointsize': NextflowParameter(
        type=float,
        default=0.1,
        section_title=None,
        description='Point size for reduced dimension plots.',
    ),
    'reddimplot_alpha': NextflowParameter(
        type=float,
        default=0.2,
        section_title=None,
        description='Alpha (transparency) value for reduced dimension plots.',
    ),
}

